version: '3.8'

services:
  collector:
    build: .
    environment:
      # Provide your own key when you run:
      - NEWS_API_KEY=${NEWS_API_KEY}
      - MAX_WIKI_ARTICLES=150
      - MAX_NEWS_ARTICLES=100
      - MAX_ARXIV_PAPERS=50
      - MAX_GOV_PAGES=60
      - MAX_GOV_DEPTH=3
      - RUN_WIKI=0
      - RUN_NEWS=0
      - RUN_ARXIV=0
      - RUN_GOV=1
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    restart: on-failure