version: '3.8'

services:
  collector:
    build: .
    environment:
      # Provide your own key when you run:
      - NEWS_API_KEY=${NEWS_API_KEY}
      - MAX_WIKI_ARTICLES=250
      - MAX_NEWS_ARTICLES=250
      - MAX_ARXIV_PAPERS=100
      - MAX_GOV_PAGES=100
      - MAX_GOV_DEPTH=5
      - RUN_WIKI=1
      - RUN_NEWS=0
      - RUN_ARXIV=0
      - RUN_GOV=0
      - WIKI_RELEVANCE_THRESHOLD=0.8
      - RUN_WIKI_COUNTRY_ONLY=1
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    restart: on-failure